### ISSUE TITLE
Random constants in GPdotNET

### ISSUE THREAD

**Issue by alidanandeh** [bhrnjica/gpdotnet#3]
I would like to see random constant values in the simplified best solution given by the program (instead of r1, r2, ….). 

![randoms](https://user-images.githubusercontent.com/45336350/48981894-44156100-f0ec-11e8-92e9-8065b79981f8.jpg)

**Comment by bhrnjica** [comment]
Constants can be easely found in the gpa file.
1. Open gpa file in notepad o notepad++
2. Search for Constants in the text. 
3. Something similar you will get: "`Constants\":[0.13744,0.88182,0.33059,.....`
4. After Constants keyword there is array of numbers which are constants.

**Comment by alidanandeh** [comment]
Thanks for the reply.  Why we cant easly see them in GpdotNET GUI?

**Comment by bhrnjica** [comment]
The feature will be implemented in the next release. 
Hope the new version will be released before spring next year.
